name: Acceptance Tests (GKE)

on:
  workflow_dispatch:
    inputs:
      region:
        description: The GKE region
        default: us-east1
      zone:
        description: The GKE zone
        default: us-east1-b
      kubernetesVersion:
        description: The GKE kubernetes version
        default: 1.24
      workersCount:
        description: The number of cluster nodes to provision
        default: 2
      nodeMachineType:
        description: The type of GKE instance to use for cluster nodes
        default: e2-standard-2
      runTests:
        description: The regex passed to the -run option of `go test`
        default: ".*"
      terraformVersion:
        description: Terraform version
        default: 1.2.8

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
  GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
  GOOGLE_REGION: ${{ github.event.inputs.region }}
  GOOGLE_ZONE: ${{github.event.inputs.zone}}
  USE_GKE_GCLOUD_AUTH_PLUGIN: True

jobs:
  prepare-gke-environment:
    name: "Prepare GKE cluster"
    permissions:
      contents: "read"
      id-token: "write"
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ${{ github.workspace }}/kubernetes/test-infra/gke/kubeconfig
    steps:
      - uses: actions/checkout@v3
      - name: Read go-version
        id: go-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.go-version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.content }}
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          access_token_lifetime: "10800s"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          install_components: "beta,gke-gcloud-auth-plugin"
      - name: "Initialize gcloud SDK"
        run: |
          gcloud init
          gcloud info
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ github.event.inputs.terraformVersion }}
          terraform_wrapper: false
      - name: Provision GKE Cluster
        working-directory: ${{ github.workspace }}/kubernetes/test-infra/gke
        env:
          TF_VAR_kubernetes_version: ${{ github.event.inputs.kubernetesVersion }}
          TF_VAR_workers_count: ${{ github.event.inputs.workersCount }}
          TF_VAR_node_machine_type: ${{ github.event.inputs.nodeMachineType }}
        run: |
          terraform init
          terraform apply -auto-approve
          export CLUSTER_NAME=`terraform output -raw cluster_name`
          echo "GOOGLE_CLUSTER_NAME=$CLUSTER_NAME" >> $GITHUB_ENV
          gcloud beta container clusters update --enable-service-externalips $CLUSTER_NAME --zone $GOOGLE_ZONE
      - name: Get GKE Credentials
        uses: "google-github-actions/get-gke-credentials@v0"
        with:
          cluster_name: ${{ env.GOOGLE_CLUSTER_NAME }}
          location: ${{github.event.inputs.zone}}
          project_id: ${{ secrets.GOOGLE_PROJECT }}
      - name: "Test cluster access"
        run: |
          kubectl cluster-info
          kubectl get nodes -owide
      - name: "Persist state"
        uses: actions/upload-artifact@v3
        with:
          name: gke-cluster
          path: |
            ${{ github.workspace }}/kubernetes/test-infra/gke/kubeconfig
            ${{ github.workspace }}/kubernetes/test-infra/gke/terraform.tfstate

  generate-case-matrix:
    name: "Generate matrix of test cases"
    runs-on: ubuntu-latest
    outputs:
      test-case-matrix: ${{ steps.generate.outputs.test-case-matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Read go-version
        id: go-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.go-version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.content }}
      - name: "Generate testcase matrix"
        id: generate
        run: |
          go test -c ./kubernetes
          echo "::set-output name=test-case-matrix::$(go run scripts/batchacc.go)"
      - name: "Persist test binary"
        uses: actions/upload-artifact@v3
        with:
          name: test-binary
          path: |
            ${{ github.workspace }}/kubernetes.test

  acceptance-tests:
    name: "Test"
    needs: [prepare-gke-environment, generate-case-matrix]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-case: ${{ fromJson(needs.generate-case-matrix.outputs.test-case-matrix) }}
    env:
      KUBECONFIG: ${{ github.workspace }}/kubernetes/test-infra/gke/kubeconfig
      KUBE_CONFIG_PATH: ${{ github.workspace }}/kubernetes/test-infra/gke/kubeconfig
    steps:
      - uses: actions/checkout@v3
      - name: Read go-version
        id: go-version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./.go-version
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.go-version.outputs.content }}
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          access_token_lifetime: "10800s"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          install_components: "beta,gke-gcloud-auth-plugin"
      - name: "Initialize gcloud SDK"
        run: |
          gcloud init
          gcloud info
      - name: "Fetch kubeconfig"
        uses: actions/download-artifact@v3
        with:
          name: gke-cluster
          path: |
            ${{ github.workspace }}/kubernetes/test-infra/gke
      - name: "Fetch test binary"
        uses: actions/download-artifact@v3
        with:
          name: test-binary
          path: |
            ${{ github.workspace }}
      - name: Run Acceptance Test
        env:
          TF_ACC_TERRAFORM_VERSION: ${{ github.event.inputs.terraformVersion }}
          TF_ACC: 1
        run: |
          chmod a+x ${{ github.workspace }}/kubernetes.test
          ${{ github.workspace }}/kubernetes.test -test.v -test.run='^${{ matrix.test-case }}$'

  clean-up:
    name: "Destroy GKE cluster"
    if: ${{ always() }}
    needs: [prepare-gke-environment, acceptance-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Retrieve state"
        uses: actions/download-artifact@v3
        with:
          name: gke-cluster
          path: |
            ${{ github.workspace }}/kubernetes/test-infra/gke
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
          access_token_lifetime: "10800s"
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ github.event.inputs.terraformVersion }}
          terraform_wrapper: false
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v0"
        with:
          install_components: "beta,gke-gcloud-auth-plugin"
      - name: "Initialize gcloud SDK"
        run: |
          gcloud init
          gcloud info
      - name: Destroy GKE cluster
        working-directory: ${{ github.workspace }}/kubernetes/test-infra/gke
        run: |
          terraform init
          terraform destroy --auto-approve
